### ISSUE TITLE
Enums in case classes not supported

### ISSUE THREAD

**Issue by larroy** [iheartradio/ficus#15]
Enums in nested case classes are not supported, I created a failing test.

I guess the macro needs to be improved.

https://github.com/larroy/ficus/commit/f1edb906513505884a8036f1affc9aab9e9ea568

**Comment by ocadaruma** [comment]
@larroy 
- You have to import `net.ceedubs.ficus.readers.EnumerationReader._` to read value as Enum, otherwise `ArbitraryTypeReader` will be used and compilation fails.
- I think `foo { EnumExample = { enum = "A" } }` is not a valid config.

This test passes.
https://gist.github.com/ocadaruma/9e649e5593080bdbd218c1e5eae398ed

**Comment by kailuowang** [comment]
Yes, as mentioned above this issue has been fixed.
